name: Neobus Ticket Hunter

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4

      - name: Przygotuj środowisko Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Zainstaluj biblioteki
        run: |
          pip install requests pandas matplotlib

      - name: Uruchom bota
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python fare_hunter.py

      - name: Wygeneruj wykresy
        run: |
          python generate_chart.py

      - name: Zapisz stan w repozytorium
        run: |
          git config --global user.name "Neobus Hunter Bot"
          git config --global user.email "bot@neobushunter.local"
          git add ceny_gliwice_domaradz.csv ceny_domaradz_gliwice.csv wykres_gliwice_domaradz.png wykres_domaradz_gliwice.png ostatnia_data_sprzedazy.txt
          git commit -m "Aktualizacja cen i wykresów obu tras [skip ci]" || echo "Brak zmian do zapisu"
          git push
